apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolligupdate-deploy
  namespace: manjulika
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 2
  minReadySeconds: 60
  selector:
    matchLabels:
      aap: nginx
  template:
    metadata:
      name: nginx-pod
      namespace: manjulika
      labels:
        aap: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
      

---
apiVersion: v1
kind: Service
metadata:
  name: recreate-svc
  namespace: manjulika
spec:
  type: NodePort
  selector:
    aap: nginx
  ports:
  - name: http
    port: 80   #<service port>
    targetPort: 80   #<container port>
    nodePort: 30032
    protocol: TCP