apiVersion: v1
kind: Pod
metadata:
  name: javapod
  namespace: nd-1
  labels:
    app: java-app
spec:
  containers:
  - name: maven-container
    image: 8983795200/java-web-app:1
    ports:
    - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: java-svc
  namespace: nd-1
spec:
  type: ClusterIP
  selector:
    app: java-app
  ports:
  - name: http
    port: 80   #<service port>
    targetPort: 8080    #<container port>
    protocol: TCP