apiVersion: v1
kind: ReplicationController
metadata:
  name: java-rc
  namespace: manjulika
spec:
  replicas: 5
  template: #Pod ka template.
    metadata:
      name: java-pod
      namespace: manjulika
      labels:
        app: royal-c
    spec:
      containers:
      - name: java-container
        image: 8983795200/java-web-app:1
        ports:
        - containerPort: 8080
        
---

apiVersion: v1
kind: Service
metadata:
  name: rc-service
  namespace: manjulika
spec:
  type: NodePort
  selectors:
    app: royal-c
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP