apiVersion: v1
kind: LimitRange
metadata:
  name: testns-limit-range
  namespace: manjulika
spec:
  limits:
  - default:
      cpu: 300m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    type: Container