apiVersion: v1
kind: Pod
metadata:
  name: mavenpod
  namespace: manjulika
spec:
  containers:
  - name: maven-container
    image: 8983795200/maven-web-application:1
    ports:
    - containerPort: 8080