apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: java-rs
  namespace: manjulika
spec:
  replicas: 3
  selector:
    matchLabels:
      app: royal-stag
  template: #Pod ka template.
    metadata:
      name: maven-pod
      namespace: manjulika
      labels:
        app: royal-stag
    spec:
      containers:
      - name: java-container
        image: 8983795200/maven-web-application:1
        ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 150m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi
        
---

apiVersion: v1
kind: Service
metadata:
  name: rs-service
  namespace: manjulika
spec:
  type: NodePort
  selector:
    app: royal-c
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP