apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-spring-boot-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-mongo-app
  template:
    metadata:
      name: spring-app-pod
      labels:
        app: spring-mongo-app
    spec:
      containers:
      - name: spring-mongo-container
        image: dockerhandson/spring-boot-mongo:1
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  type: NodePort
  selector:
    app: spring-mongo-app
  ports:
  - name: http
    port: 80   #<service port>
    targetPort: 8080   #<container port>
    nodePort: 30032
    protocol: TCP