apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 1Gi

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-sc
provisioner: ebs.csi.aws.com
parameters:
  type: gp2
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-spring-boot-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-mongo-app
  template:
    metadata:
      name: spring-app-pod
      labels:
        app: spring-mongo-app
    spec:
      containers:
      - name: spring-mongo-container
        image: dockerhandson/spring-boot-mongo:1
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_USERNAME
          value: monika
        - name: MONGO_DB_PASSWORD
          value: monika@567
        - name: MONGO_DB_HOSTNAME
          value: mongo

---
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  type: NodePort
  selector:
    app: spring-mongo-app
  ports:
  - name: http
    port: 80   #<service port>
    targetPort: 8080   #<container port>
    nodePort: 30032
    protocol: TCP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      name: mongodb-pod
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb-container
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: monika
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: monika@567
        volumeMounts:
        - name: monikavolume
          mountPath: /data/db
      volumes:
      - name: monikavolume
        persistentVolumeClaim:
          claimName: ebs-claim

---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: mongo
  ports:
  - name: http
    port: 27017  #<service port>
    targetPort: 27017   #<container port>
    protocol: TCP